"""empty message

Revision ID: 064c8eed19ce
Revises: 7f5a8ad73fce
Create Date: 2017-01-12 15:49:42.147282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064c8eed19ce'
down_revision = '7f5a8ad73fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
