"""empty message

Revision ID: 7f5a8ad73fce
Revises: c76b10c921a9
Create Date: 2017-01-10 16:06:54.066554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5a8ad73fce'
down_revision = 'c76b10c921a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('rating', sa.Float(precision=10), nullable=True))
    op.drop_index('name', table_name='point')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'point', ['name'], unique=True)
    op.drop_column('point', 'rating')
    # ### end Alembic commands ###
