"""empty message

Revision ID: c76b10c921a9
Revises: 43fe770f6785
Create Date: 2016-12-26 00:40:08.621092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c76b10c921a9'
down_revision = '43fe770f6785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('point_ibfk_1', 'point', type_='foreignkey')
    op.create_foreign_key(None, 'point', 'user', ['author_id'], ['id'])
    op.drop_column('point', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'point', type_='foreignkey')
    op.create_foreign_key('point_ibfk_1', 'point', 'user', ['author'], ['id'])
    op.drop_column('point', 'author_id')
    # ### end Alembic commands ###
